baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Digital Fabrication Project'
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  GithubID = "your_github"
 

 
  Name = "Ata"
  HeaderUsername = "Ata"
  HeaderHostname = "gohugo.io"
  Email = "your_email"
  About = "Hi I'm Ata and this is my website. I am a digital fabrication student."
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
