baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Digital Fabrication Project'
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "assignments"
    weight = 0
    pageRef = "/posts"

[params]
  GithubID = "fahirataalaca"
  Name = "Ata"
  HeaderUsername = "Ata"
  HeaderHostname = "ideaLab"
  Email = "ata.alaca@hisarschool.k12.tr"
  About = "Hi I'm Ata and this is my website. I am a digital fabrication student."
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
